application: laxcrime
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /public
  static_dir: public

- url: /upload_information
  script: controllers.UploadInformation.app
  login: admin
  
- url: /create_default_information
  script: controllers.CreateDefaultInformation.app
  login: admin
  
- url: /retrieve-incident-latlong
  script: controllers.RetrieveIncidentLatLong.app
  
- url: /get_incident_reports
  script: controllers.GetIncidentReports.app

- url: /
  script: controllers.Main.app
  login: admin

  
libraries:
- name: webapp2
  version: "2.5.1"
